//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClients
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facturacion.finkok.com/registration", ConfigurationName="ServiceClients.Application")]
    public interface Application
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="edit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceClients.editResponse1> editAsync(ServiceClients.edit1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceClients.addResponse1> addAsync(ServiceClients.add1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="assign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceClients.assignResponse1> assignAsync(ServiceClients.assign1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="switch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceClients.switchResponse1> switchAsync(ServiceClients.switch1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceClients.getResponse1> getAsync(ServiceClients.get1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class edit
    {
        
        private string reseller_usernameField;
        
        private string reseller_passwordField;
        
        private string taxpayer_idField;
        
        private string statusField;
        
        private byte[] cerField;
        
        private byte[] keyField;
        
        private string passphraseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string reseller_username
        {
            get
            {
                return this.reseller_usernameField;
            }
            set
            {
                this.reseller_usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string reseller_password
        {
            get
            {
                return this.reseller_passwordField;
            }
            set
            {
                this.reseller_passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string taxpayer_id
        {
            get
            {
                return this.taxpayer_idField;
            }
            set
            {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=4)]
        public byte[] cer
        {
            get
            {
                return this.cerField;
            }
            set
            {
                this.cerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=5)]
        public byte[] key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string passphrase
        {
            get
            {
                return this.passphraseField;
            }
            set
            {
                this.passphraseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ResellerUser
    {
        
        private string statusField;
        
        private string counterField;
        
        private string taxpayer_idField;
        
        private string creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string counter
        {
            get
            {
                return this.counterField;
            }
            set
            {
                this.counterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string taxpayer_id
        {
            get
            {
                return this.taxpayer_idField;
            }
            set
            {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=3)]
        public string credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class RegistrationListResult
    {
        
        private string messageField;
        
        private ResellerUser[] usersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public ResellerUser[] users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class getResponse
    {
        
        private RegistrationListResult getResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public RegistrationListResult getResult
        {
            get
            {
                return this.getResultField;
            }
            set
            {
                this.getResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class get
    {
        
        private string reseller_usernameField;
        
        private string reseller_passwordField;
        
        private string taxpayer_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string reseller_username
        {
            get
            {
                return this.reseller_usernameField;
            }
            set
            {
                this.reseller_usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string reseller_password
        {
            get
            {
                return this.reseller_passwordField;
            }
            set
            {
                this.reseller_passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string taxpayer_id
        {
            get
            {
                return this.taxpayer_idField;
            }
            set
            {
                this.taxpayer_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class SwitchResult
    {
        
        private string messageField;
        
        private System.Nullable<bool> successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified
        {
            get
            {
                return this.successFieldSpecified;
            }
            set
            {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class switchResponse
    {
        
        private SwitchResult switchResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public SwitchResult switchResult
        {
            get
            {
                return this.switchResultField;
            }
            set
            {
                this.switchResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class @switch
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private string type_userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string taxpayer_id
        {
            get
            {
                return this.taxpayer_idField;
            }
            set
            {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string type_user
        {
            get
            {
                return this.type_userField;
            }
            set
            {
                this.type_userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class AssingResult
    {
        
        private System.Nullable<bool> successField;
        
        private bool successFieldSpecified;
        
        private string creditField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified
        {
            get
            {
                return this.successFieldSpecified;
            }
            set
            {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class assignResponse
    {
        
        private AssingResult assignResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AssingResult assignResult
        {
            get
            {
                return this.assignResultField;
            }
            set
            {
                this.assignResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class assign
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private string creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string taxpayer_id
        {
            get
            {
                return this.taxpayer_idField;
            }
            set
            {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", IsNullable=true, Order=3)]
        public string credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class addResponse
    {
        
        private RegistrationResult addResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public RegistrationResult addResult
        {
            get
            {
                return this.addResultField;
            }
            set
            {
                this.addResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class RegistrationResult
    {
        
        private string messageField;
        
        private System.Nullable<bool> successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified
        {
            get
            {
                return this.successFieldSpecified;
            }
            set
            {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class add
    {
        
        private string reseller_usernameField;
        
        private string reseller_passwordField;
        
        private string taxpayer_idField;
        
        private string type_userField;
        
        private string couponField;
        
        private string addedField;
        
        private byte[] cerField;
        
        private byte[] keyField;
        
        private string passphraseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string reseller_username
        {
            get
            {
                return this.reseller_usernameField;
            }
            set
            {
                this.reseller_usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string reseller_password
        {
            get
            {
                return this.reseller_passwordField;
            }
            set
            {
                this.reseller_passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string taxpayer_id
        {
            get
            {
                return this.taxpayer_idField;
            }
            set
            {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string type_user
        {
            get
            {
                return this.type_userField;
            }
            set
            {
                this.type_userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string coupon
        {
            get
            {
                return this.couponField;
            }
            set
            {
                this.couponField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=6)]
        public byte[] cer
        {
            get
            {
                return this.cerField;
            }
            set
            {
                this.cerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=7)]
        public byte[] key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string passphrase
        {
            get
            {
                return this.passphraseField;
            }
            set
            {
                this.passphraseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/registration")]
    public partial class editResponse
    {
        
        private RegistrationResult editResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public RegistrationResult editResult
        {
            get
            {
                return this.editResultField;
            }
            set
            {
                this.editResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class edit1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.edit edit;
        
        public edit1()
        {
        }
        
        public edit1(ServiceClients.edit edit)
        {
            this.edit = edit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.editResponse editResponse;
        
        public editResponse1()
        {
        }
        
        public editResponse1(ServiceClients.editResponse editResponse)
        {
            this.editResponse = editResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class add1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.add add;
        
        public add1()
        {
        }
        
        public add1(ServiceClients.add add)
        {
            this.add = add;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.addResponse addResponse;
        
        public addResponse1()
        {
        }
        
        public addResponse1(ServiceClients.addResponse addResponse)
        {
            this.addResponse = addResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class assign1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.assign assign;
        
        public assign1()
        {
        }
        
        public assign1(ServiceClients.assign assign)
        {
            this.assign = assign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class assignResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.assignResponse assignResponse;
        
        public assignResponse1()
        {
        }
        
        public assignResponse1(ServiceClients.assignResponse assignResponse)
        {
            this.assignResponse = assignResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class switch1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.@switch @switch;
        
        public switch1()
        {
        }
        
        public switch1(ServiceClients.@switch @switch)
        {
            this.@switch = @switch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class switchResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.switchResponse switchResponse;
        
        public switchResponse1()
        {
        }
        
        public switchResponse1(ServiceClients.switchResponse switchResponse)
        {
            this.switchResponse = switchResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.get get;
        
        public get1()
        {
        }
        
        public get1(ServiceClients.get get)
        {
            this.get = get;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/registration", Order=0)]
        public ServiceClients.getResponse getResponse;
        
        public getResponse1()
        {
        }
        
        public getResponse1(ServiceClients.getResponse getResponse)
        {
            this.getResponse = getResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ApplicationChannel : ServiceClients.Application, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<ServiceClients.Application>, ServiceClients.Application
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApplicationClient() : 
                base(ApplicationClient.GetDefaultBinding(), ApplicationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Application.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), ApplicationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClients.editResponse1> ServiceClients.Application.editAsync(ServiceClients.edit1 request)
        {
            return base.Channel.editAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClients.editResponse1> editAsync(ServiceClients.edit edit)
        {
            ServiceClients.edit1 inValue = new ServiceClients.edit1();
            inValue.edit = edit;
            return ((ServiceClients.Application)(this)).editAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClients.addResponse1> ServiceClients.Application.addAsync(ServiceClients.add1 request)
        {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClients.addResponse1> addAsync(ServiceClients.add add)
        {
            ServiceClients.add1 inValue = new ServiceClients.add1();
            inValue.add = add;
            return ((ServiceClients.Application)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClients.assignResponse1> ServiceClients.Application.assignAsync(ServiceClients.assign1 request)
        {
            return base.Channel.assignAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClients.assignResponse1> assignAsync(ServiceClients.assign assign)
        {
            ServiceClients.assign1 inValue = new ServiceClients.assign1();
            inValue.assign = assign;
            return ((ServiceClients.Application)(this)).assignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClients.switchResponse1> ServiceClients.Application.switchAsync(ServiceClients.switch1 request)
        {
            return base.Channel.switchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClients.switchResponse1> switchAsync(ServiceClients.@switch @switch)
        {
            ServiceClients.switch1 inValue = new ServiceClients.switch1();
            inValue.@switch = @switch;
            return ((ServiceClients.Application)(this)).switchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClients.getResponse1> ServiceClients.Application.getAsync(ServiceClients.get1 request)
        {
            return base.Channel.getAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClients.getResponse1> getAsync(ServiceClients.get get)
        {
            ServiceClients.get1 inValue = new ServiceClients.get1();
            inValue.get = get;
            return ((ServiceClients.Application)(this)).getAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                return new System.ServiceModel.EndpointAddress("https://demo-facturacion.finkok.com/servicios/soap/registration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApplicationClient.GetBindingForEndpoint(EndpointConfiguration.Application);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApplicationClient.GetEndpointAddress(EndpointConfiguration.Application);
        }
        
        public enum EndpointConfiguration
        {
            
            Application,
        }
    }
}
