//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactureyaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaTFD33", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaTFD33 : object
    {
        
        private string CodigoConfirmacionField;
        
        private string CodigoRespuestaField;
        
        private int CreditosRestantesField;
        
        private string MensajeErrorField;
        
        private string MensajeErrorDetalladoField;
        
        private bool OperacionExitosaField;
        
        private string PDFResultadoField;
        
        private FactureyaService.Timbre33 TimbreField;
        
        private string XMLResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoConfirmacion
        {
            get
            {
                return this.CodigoConfirmacionField;
            }
            set
            {
                this.CodigoConfirmacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta
        {
            get
            {
                return this.CodigoRespuestaField;
            }
            set
            {
                this.CodigoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditosRestantes
        {
            get
            {
                return this.CreditosRestantesField;
            }
            set
            {
                this.CreditosRestantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado
        {
            get
            {
                return this.MensajeErrorDetalladoField;
            }
            set
            {
                this.MensajeErrorDetalladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PDFResultado
        {
            get
            {
                return this.PDFResultadoField;
            }
            set
            {
                this.PDFResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.Timbre33 Timbre
        {
            get
            {
                return this.TimbreField;
            }
            set
            {
                this.TimbreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLResultado
        {
            get
            {
                return this.XMLResultadoField;
            }
            set
            {
                this.XMLResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timbre33", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class Timbre33 : object
    {
        
        private string EstadoField;
        
        private System.DateTime FechaTimbradoField;
        
        private string NumeroCertificadoSATField;
        
        private string SelloCFDField;
        
        private string SelloSATField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTimbrado
        {
            get
            {
                return this.FechaTimbradoField;
            }
            set
            {
                this.FechaTimbradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCertificadoSAT
        {
            get
            {
                return this.NumeroCertificadoSATField;
            }
            set
            {
                this.NumeroCertificadoSATField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelloCFD
        {
            get
            {
                return this.SelloCFDField;
            }
            set
            {
                this.SelloCFDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelloSAT
        {
            get
            {
                return this.SelloSATField;
            }
            set
            {
                this.SelloSATField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCFDICancelacion", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class DetalleCFDICancelacion : object
    {
        
        private string EsCancelableField;
        
        private string FolioSustitucionField;
        
        private string MotivoField;
        
        private string RFCReceptorField;
        
        private decimal TotalField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsCancelable
        {
            get
            {
                return this.EsCancelableField;
            }
            set
            {
                this.EsCancelableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioSustitucion
        {
            get
            {
                return this.FolioSustitucionField;
            }
            set
            {
                this.FolioSustitucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCReceptor
        {
            get
            {
                return this.RFCReceptorField;
            }
            set
            {
                this.RFCReceptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacion", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaCancelacion : object
    {
        
        private FactureyaService.DetalleCancelacion[] DetallesCancelacionField;
        
        private string MensajeErrorField;
        
        private string MensajeErrorDetalladoField;
        
        private bool OperacionExitosaField;
        
        private string XMLAcuseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.DetalleCancelacion[] DetallesCancelacion
        {
            get
            {
                return this.DetallesCancelacionField;
            }
            set
            {
                this.DetallesCancelacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado
        {
            get
            {
                return this.MensajeErrorDetalladoField;
            }
            set
            {
                this.MensajeErrorDetalladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLAcuse
        {
            get
            {
                return this.XMLAcuseField;
            }
            set
            {
                this.XMLAcuseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCancelacion", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class DetalleCancelacion : object
    {
        
        private string CodigoResultadoField;
        
        private string EsCancelableField;
        
        private string MensajeResultadoField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoResultado
        {
            get
            {
                return this.CodigoResultadoField;
            }
            set
            {
                this.CodigoResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsCancelable
        {
            get
            {
                return this.EsCancelableField;
            }
            set
            {
                this.EsCancelableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeResultado
        {
            get
            {
                return this.MensajeResultadoField;
            }
            set
            {
                this.MensajeResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacionAsincrona", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaCancelacionAsincrona : object
    {
        
        private FactureyaService.DetalleCancelacion[] DetallesCancelacionField;
        
        private string MensajeErrorField;
        
        private bool OperacionExitosaField;
        
        private string ReferenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.DetalleCancelacion[] DetallesCancelacion
        {
            get
            {
                return this.DetallesCancelacionField;
            }
            set
            {
                this.DetallesCancelacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia
        {
            get
            {
                return this.ReferenciaField;
            }
            set
            {
                this.ReferenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaEstatusCancelacionAsincrona", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaEstatusCancelacionAsincrona : object
    {
        
        private string EstatusField;
        
        private string MensajeErrorField;
        
        private bool OperacionExitosaField;
        
        private string ReferenciaField;
        
        private string XMLAcuseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estatus
        {
            get
            {
                return this.EstatusField;
            }
            set
            {
                this.EstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia
        {
            get
            {
                return this.ReferenciaField;
            }
            set
            {
                this.ReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLAcuse
        {
            get
            {
                return this.XMLAcuseField;
            }
            set
            {
                this.XMLAcuseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCreditos", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaCreditos : object
    {
        
        private string MensajeErrorField;
        
        private bool OperacionExitosaField;
        
        private FactureyaService.DetallesPaqueteCreditos[] PaquetesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.DetallesPaqueteCreditos[] Paquetes
        {
            get
            {
                return this.PaquetesField;
            }
            set
            {
                this.PaquetesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallesPaqueteCreditos", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class DetallesPaqueteCreditos : object
    {
        
        private bool EnUsoField;
        
        private System.Nullable<System.DateTime> FechaActivacionField;
        
        private System.Nullable<System.DateTime> FechaVencimientoField;
        
        private string PaqueteField;
        
        private int TimbresField;
        
        private int TimbresRestantesField;
        
        private int TimbresUsadosField;
        
        private bool VigenteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnUso
        {
            get
            {
                return this.EnUsoField;
            }
            set
            {
                this.EnUsoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaActivacion
        {
            get
            {
                return this.FechaActivacionField;
            }
            set
            {
                this.FechaActivacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paquete
        {
            get
            {
                return this.PaqueteField;
            }
            set
            {
                this.PaqueteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timbres
        {
            get
            {
                return this.TimbresField;
            }
            set
            {
                this.TimbresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresRestantes
        {
            get
            {
                return this.TimbresRestantesField;
            }
            set
            {
                this.TimbresRestantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresUsados
        {
            get
            {
                return this.TimbresUsadosField;
            }
            set
            {
                this.TimbresUsadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vigente
        {
            get
            {
                return this.VigenteField;
            }
            set
            {
                this.VigenteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaReporte", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaReporte : object
    {
        
        private FactureyaService.RegistroTimbre[] ListaComprobantesField;
        
        private string MensajeErrorField;
        
        private bool OperacionExitosaField;
        
        private int TotalComprobantesPeriodoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.RegistroTimbre[] ListaComprobantes
        {
            get
            {
                return this.ListaComprobantesField;
            }
            set
            {
                this.ListaComprobantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalComprobantesPeriodo
        {
            get
            {
                return this.TotalComprobantesPeriodoField;
            }
            set
            {
                this.TotalComprobantesPeriodoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroTimbre", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RegistroTimbre : object
    {
        
        private string EstadoField;
        
        private System.DateTime FechaTimbradoField;
        
        private int NoFilaField;
        
        private string RFCEmisorField;
        
        private string RFCReceptorField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTimbrado
        {
            get
            {
                return this.FechaTimbradoField;
            }
            set
            {
                this.FechaTimbradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoFila
        {
            get
            {
                return this.NoFilaField;
            }
            set
            {
                this.NoFilaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCEmisor
        {
            get
            {
                return this.RFCEmisorField;
            }
            set
            {
                this.RFCEmisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCReceptor
        {
            get
            {
                return this.RFCReceptorField;
            }
            set
            {
                this.RFCReceptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaValidacionRFC", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaValidacionRFC : object
    {
        
        private bool CanceladoField;
        
        private string MensajeErrorField;
        
        private string RFCField;
        
        private bool RFCLocalizadoField;
        
        private bool SubcontratacionField;
        
        private bool UnidadSNCFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cancelado
        {
            get
            {
                return this.CanceladoField;
            }
            set
            {
                this.CanceladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RFCLocalizado
        {
            get
            {
                return this.RFCLocalizadoField;
            }
            set
            {
                this.RFCLocalizadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Subcontratacion
        {
            get
            {
                return this.SubcontratacionField;
            }
            set
            {
                this.SubcontratacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UnidadSNCF
        {
            get
            {
                return this.UnidadSNCFField;
            }
            set
            {
                this.UnidadSNCFField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaBase", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FactureyaService.RespuestaAceptacionRechazo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FactureyaService.RespuestaPeticionesPendientes))]
    public partial class RespuestaBase : object
    {
        
        private string CodigoRespuestaField;
        
        private string MensajeErrorField;
        
        private string MensajeErrorDetalladoField;
        
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta
        {
            get
            {
                return this.CodigoRespuestaField;
            }
            set
            {
                this.CodigoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado
        {
            get
            {
                return this.MensajeErrorDetalladoField;
            }
            set
            {
                this.MensajeErrorDetalladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaAceptacionRechazo", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaAceptacionRechazo : FactureyaService.RespuestaBase
    {
        
        private System.DateTime FechaField;
        
        private FactureyaService.FolioRespuesta[] FoliosField;
        
        private string RFCReceptorField;
        
        private string XMLAcuseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.FolioRespuesta[] Folios
        {
            get
            {
                return this.FoliosField;
            }
            set
            {
                this.FoliosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCReceptor
        {
            get
            {
                return this.RFCReceptorField;
            }
            set
            {
                this.RFCReceptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLAcuse
        {
            get
            {
                return this.XMLAcuseField;
            }
            set
            {
                this.XMLAcuseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaPeticionesPendientes", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaPeticionesPendientes : FactureyaService.RespuestaBase
    {
        
        private string[] UUIDsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] UUIDs
        {
            get
            {
                return this.UUIDsField;
            }
            set
            {
                this.UUIDsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class FolioRespuesta : object
    {
        
        private string EstatusUUIDField;
        
        private string RespuestaField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstatusUUID
        {
            get
            {
                return this.EstatusUUIDField;
            }
            set
            {
                this.EstatusUUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UUIDProcesarRespuesta", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class UUIDProcesarRespuesta : object
    {
        
        private bool AceptarField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptar
        {
            get
            {
                return this.AceptarField;
            }
            set
            {
                this.AceptarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaRelacionados", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class RespuestaRelacionados : object
    {
        
        private string MensajeErrorField;
        
        private bool OperacionExitosaField;
        
        private FactureyaService.Relacionados RelacionadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa
        {
            get
            {
                return this.OperacionExitosaField;
            }
            set
            {
                this.OperacionExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.Relacionados Relacionados
        {
            get
            {
                return this.RelacionadosField;
            }
            set
            {
                this.RelacionadosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relacionados", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class Relacionados : object
    {
        
        private string ResultadoField;
        
        private string UuidConsultadoField;
        
        private FactureyaService.UUID[] UuidsRelacionadosHijosField;
        
        private FactureyaService.UUID[] UuidsRelacionadosPadresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UuidConsultado
        {
            get
            {
                return this.UuidConsultadoField;
            }
            set
            {
                this.UuidConsultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.UUID[] UuidsRelacionadosHijos
        {
            get
            {
                return this.UuidsRelacionadosHijosField;
            }
            set
            {
                this.UuidsRelacionadosHijosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactureyaService.UUID[] UuidsRelacionadosPadres
        {
            get
            {
                return this.UuidsRelacionadosPadresField;
            }
            set
            {
                this.UuidsRelacionadosPadresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UUID", Namespace="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios")]
    public partial class UUID : object
    {
        
        private string RfcEmisorField;
        
        private string RfcReceptorField;
        
        private string UuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcEmisor
        {
            get
            {
                return this.RfcEmisorField;
            }
            set
            {
                this.RfcEmisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcReceptor
        {
            get
            {
                return this.RfcReceptorField;
            }
            set
            {
                this.RfcReceptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid
        {
            get
            {
                return this.UuidField;
            }
            set
            {
                this.UuidField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FactureyaService.IWSCFDI33")]
    public interface IWSCFDI33
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/TimbrarCFDI", ReplyAction="http://tempuri.org/IWSCFDI33/TimbrarCFDIResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> TimbrarCFDIAsync(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/CancelarCFDI", ReplyAction="http://tempuri.org/IWSCFDI33/CancelarCFDIResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaCancelacion> CancelarCFDIAsync(string usuario, string password, string rFCEmisor, FactureyaService.DetalleCFDICancelacion[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/CancelacionAsincrona", ReplyAction="http://tempuri.org/IWSCFDI33/CancelacionAsincronaResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaCancelacionAsincrona> CancelacionAsincronaAsync(string usuario, string password, string rFCEmisor, string[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincrona", ReplyAction="http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincronaResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaEstatusCancelacionAsincrona> EstatusCancelacionAsincronaAsync(string usuario, string password, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ObtenerPDF", ReplyAction="http://tempuri.org/IWSCFDI33/ObtenerPDFResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ObtenerPDFAsync(string usuario, string password, string uUID, string LogoBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvio", ReplyAction="http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvioResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ObtenerAcuseEnvioAsync(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacion", ReplyAction="http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacionResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ObtenerAcuseCancelacionAsync(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/CambiarPassword", ReplyAction="http://tempuri.org/IWSCFDI33/CambiarPasswordResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> CambiarPasswordAsync(string usuario, string passwordActual, string passwordNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbre", ReplyAction="http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbreResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ConsultarComplementoTimbreAsync(string usuario, string password, string uUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferencia", ReplyAction="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferenciaResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ConsultarTimbrePorReferenciaAsync(string usuario, string password, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorSello", ReplyAction="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorSelloResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ConsultarTimbrePorSelloAsync(string usuario, string password, string sello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ConsultarCreditos", ReplyAction="http://tempuri.org/IWSCFDI33/ConsultarCreditosResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaCreditos> ConsultarCreditosAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ConsultarComprobantes", ReplyAction="http://tempuri.org/IWSCFDI33/ConsultarComprobantesResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaReporte> ConsultarComprobantesAsync(string usuario, string password, System.DateTime fechaInicial, System.DateTime fechaFinal, int filaInicial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ValidarRFC", ReplyAction="http://tempuri.org/IWSCFDI33/ValidarRFCResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaValidacionRFC> ValidarRFCAsync(string usuario, string password, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ObtenerPeticionesPendientesCancelacion", ReplyAction="http://tempuri.org/IWSCFDI33/ObtenerPeticionesPendientesCancelacionResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaPeticionesPendientes> ObtenerPeticionesPendientesCancelacionAsync(string usuario, string password, string rFCReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ProcesarAceptacionRechazo", ReplyAction="http://tempuri.org/IWSCFDI33/ProcesarAceptacionRechazoResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaAceptacionRechazo> ProcesarAceptacionRechazoAsync(string usuario, string password, string rFCReceptor, FactureyaService.UUIDProcesarRespuesta[] uUIDs, string clavePrivada_Base64, string passwordClavePrivada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/CancelarCFDIConValidacion", ReplyAction="http://tempuri.org/IWSCFDI33/CancelarCFDIConValidacionResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaCancelacion> CancelarCFDIConValidacionAsync(string usuario, string password, string rFCEmisor, FactureyaService.DetalleCFDICancelacion[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCFDI33/ConsultarComprobantesRelacionados", ReplyAction="http://tempuri.org/IWSCFDI33/ConsultarComprobantesRelacionadosResponse")]
        System.Threading.Tasks.Task<FactureyaService.RespuestaRelacionados> ConsultarComprobantesRelacionadosAsync(string usuario, string password, string UUID, string RFCReceptor, string RFCEmisor, string pfxReceptorBase64, string passwdPfx);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWSCFDI33Channel : FactureyaService.IWSCFDI33, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WSCFDI33Client : System.ServiceModel.ClientBase<FactureyaService.IWSCFDI33>, FactureyaService.IWSCFDI33
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSCFDI33Client() : 
                base(WSCFDI33Client.GetDefaultBinding(), WSCFDI33Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.soapHttpEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCFDI33Client(EndpointConfiguration endpointConfiguration) : 
                base(WSCFDI33Client.GetBindingForEndpoint(endpointConfiguration), WSCFDI33Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCFDI33Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSCFDI33Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCFDI33Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSCFDI33Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCFDI33Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> TimbrarCFDIAsync(string usuario, string password, string cadenaXML, string referencia)
        {
            return base.Channel.TimbrarCFDIAsync(usuario, password, cadenaXML, referencia);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaCancelacion> CancelarCFDIAsync(string usuario, string password, string rFCEmisor, FactureyaService.DetalleCFDICancelacion[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada)
        {
            return base.Channel.CancelarCFDIAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaCancelacionAsincrona> CancelacionAsincronaAsync(string usuario, string password, string rFCEmisor, string[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada)
        {
            return base.Channel.CancelacionAsincronaAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaEstatusCancelacionAsincrona> EstatusCancelacionAsincronaAsync(string usuario, string password, string referencia)
        {
            return base.Channel.EstatusCancelacionAsincronaAsync(usuario, password, referencia);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ObtenerPDFAsync(string usuario, string password, string uUID, string LogoBase64)
        {
            return base.Channel.ObtenerPDFAsync(usuario, password, uUID, LogoBase64);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ObtenerAcuseEnvioAsync(string usuario, string password, string uUID)
        {
            return base.Channel.ObtenerAcuseEnvioAsync(usuario, password, uUID);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ObtenerAcuseCancelacionAsync(string usuario, string password, string uUID)
        {
            return base.Channel.ObtenerAcuseCancelacionAsync(usuario, password, uUID);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> CambiarPasswordAsync(string usuario, string passwordActual, string passwordNuevo)
        {
            return base.Channel.CambiarPasswordAsync(usuario, passwordActual, passwordNuevo);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ConsultarComplementoTimbreAsync(string usuario, string password, string uUID)
        {
            return base.Channel.ConsultarComplementoTimbreAsync(usuario, password, uUID);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ConsultarTimbrePorReferenciaAsync(string usuario, string password, string referencia)
        {
            return base.Channel.ConsultarTimbrePorReferenciaAsync(usuario, password, referencia);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaTFD33> ConsultarTimbrePorSelloAsync(string usuario, string password, string sello)
        {
            return base.Channel.ConsultarTimbrePorSelloAsync(usuario, password, sello);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaCreditos> ConsultarCreditosAsync(string usuario, string password)
        {
            return base.Channel.ConsultarCreditosAsync(usuario, password);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaReporte> ConsultarComprobantesAsync(string usuario, string password, System.DateTime fechaInicial, System.DateTime fechaFinal, int filaInicial)
        {
            return base.Channel.ConsultarComprobantesAsync(usuario, password, fechaInicial, fechaFinal, filaInicial);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaValidacionRFC> ValidarRFCAsync(string usuario, string password, string rfc)
        {
            return base.Channel.ValidarRFCAsync(usuario, password, rfc);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaPeticionesPendientes> ObtenerPeticionesPendientesCancelacionAsync(string usuario, string password, string rFCReceptor)
        {
            return base.Channel.ObtenerPeticionesPendientesCancelacionAsync(usuario, password, rFCReceptor);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaAceptacionRechazo> ProcesarAceptacionRechazoAsync(string usuario, string password, string rFCReceptor, FactureyaService.UUIDProcesarRespuesta[] uUIDs, string clavePrivada_Base64, string passwordClavePrivada)
        {
            return base.Channel.ProcesarAceptacionRechazoAsync(usuario, password, rFCReceptor, uUIDs, clavePrivada_Base64, passwordClavePrivada);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaCancelacion> CancelarCFDIConValidacionAsync(string usuario, string password, string rFCEmisor, FactureyaService.DetalleCFDICancelacion[] listaCFDI, string clavePrivada_Base64, string passwordClavePrivada)
        {
            return base.Channel.CancelarCFDIConValidacionAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada);
        }
        
        public System.Threading.Tasks.Task<FactureyaService.RespuestaRelacionados> ConsultarComprobantesRelacionadosAsync(string usuario, string password, string UUID, string RFCReceptor, string RFCEmisor, string pfxReceptorBase64, string passwdPfx)
        {
            return base.Channel.ConsultarComprobantesRelacionadosAsync(usuario, password, UUID, RFCReceptor, RFCEmisor, pfxReceptorBase64, passwdPfx);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.soapHttpEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.soapHttpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://app.factureyapac.com/WSTimbrado33Test/WSCFDI33.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSCFDI33Client.GetBindingForEndpoint(EndpointConfiguration.soapHttpEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSCFDI33Client.GetEndpointAddress(EndpointConfiguration.soapHttpEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            soapHttpEndpoint,
        }
    }
}
